version: "3.7"
services:
    cups:
        image: anujdatar/cups
        container_name: cups
        restart: unless-stopped
        ports:
            - "631:631"
        devices:
            - /dev/bus/usb:/dev/bus/usb
        environment:
            - CUPSADMIN=xxx
            - CUPSPASSWORD=yyy
            - TZ=Etc/UTC
volumes:
  cups_config:
  cups_spool:
  cups_log:
