services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - TZ=Asia/Kolkata
      - PORT=5055
      # - LOG_LEVEL=debug
    ports:
      - 5055:5055
    volumes:
      - ./jellyseerr_config:/app/config
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    name: web
    external: true
